name = "Sylveon Brass"
author = "xpudding736"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8edbd4cce8d4aa27d31fc722055400ba922855695b72853e73f29f0cb9fc244"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
