name = "Sylveon Brass"
author = "xpudding736"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e54034bc55c736be8d03493855b4ca5341f4d1dc1f2a4d5a45f88da4d17d52c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
