name = "Sylveon Brass"
author = "xpudding736"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1f69e767712e56fa9241af5ef9bb91d5b92f2c42ea68908d8b0daf8b0a51f01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
